services:
  - type: web
    name: your-laravel-app
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-database-host
      - key: DB_DATABASE
        value: book-review
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: your-password
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php-fpm
    initialDeployHook: ./seed_database.sh